<a href="https://colab.research.google.com/github/jyothijoo197-ui/datasciencelearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np
#1d array
l = [1,2,3,4,5]
print(l)
print("type of list", type(l))
#after converting into list
l = np.array(l)
print(l)
print("type of array", type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
type of list <class 'list'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [3]:
#creating 2d arrays
l1 = [1,2,3,4,5]
l2 = [3,4,5,6,7]
l3 = [5,6,7,8,9]
l4 = np.array([
    l1,
    l2,
    l3
])
print(l4)
print(l4.ndim)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]
2


In [4]:
l1 = [
  [1,2],
  [3,4]
]
l2 = [
  [1,2],
  [3,4]
]
l3 = np.array([
    l1,l2
])
print(l3)
print(l3.ndim)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3


In [5]:
print("hello world!")

hello world!


In [ ]:
# there are different types of Using arrays

In [6]:
#different Ways to Create Arraya in Numpy
#using array
l = [1,2,3,4,5]
p = (1,2,3,4,5)
l = np.array(l)
p = np.array(p)
print("list converted into array")
print(l)
print("tuple converted into array")
print(p)

list converted into array
[1 2 3 4 5]
tuple converted into array
[1 2 3 4 5]


In [7]:
#fromiter
l = [1,2,3,4,5]
arr = np.fromiter(l, dtype=int)
print(arr)

[1 2 3 4 5]


In [8]:
#arange
l = np.arange(5)
print(l)
l = np.arange(1,9)
print(l)
l = np.arange(1,10,2)
print(l)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [9]:
arr = np.linspace(1,5,8)
print(arr)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [12]:
arr = np.empty((5,3))
print(arr)

[[3.50460836e-315 0.00000000e+000 1.58898665e-258]
 [3.68777421e+180 4.47593816e-091 2.93573416e+222]
 [7.35981919e+223 3.21142670e-322 6.85887921e-310]
 [6.85887921e-310 1.03063392e-113 5.15249973e-062]
 [2.99067257e-067 3.50443730e-033 1.42290906e-321]]


In [13]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


zeros and ones we will use in the deep learning tech

In [14]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.shape) # if we want to know the number of rows and columns we will use this shape property
print(arr.ndim) # if we want to know the dimension of an array we will use ndim property
print(arr.dtype) # if we want to know the datatype of an array we will use dtype property

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
2
int64


In [20]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.sum(axis =0))
print(arr.sum(axis =1))

[[1 2 3 4 5]
 [4 5 6 7 8]]
[ 5  7  9 11 13]
[15 30]


In [21]:
#indexing : accessing the elements
l = [10,20,30,40]
arr = np.array(l)
print(arr[3])
print(arr[0])
print(arr[1])
print(arr[-1])

40
10
20
40


In [23]:
l2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[1,0])
print(l2[0])
print(l2[1])
print(l2[2])
print(l2[:,0])
print(l2[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
4
[1 2 3]
[4 5 6]
[7 8 9]
[1 4 7]
[2 5 8]


In [25]:
# l[start:end:step]
l = [1,2,3,4,5]
arr = np.array(l)
print(arr)
print(arr[0:2])
print(arr[0:5])
print(arr[1:5])
print(arr[0:5:2])
print(arr[1:])
print(arr[:4])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[2 3 4 5]
[1 3 5]
[2 3 4 5]
[1 2 3 4]


In [27]:
#l[row_start:row_end, col_start:col_end]
l = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11]
])
print(l)
print(l[0:2,0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]]
